### ISSUE TITLE
Xposed 日志报错 ClassNotFoundException

### ISSUE THREAD

**Issue by litangyu** [2449983723/alipay-master#1]
如题，点击收款后，无法调起收款界面

04-16 18:38:44.686 I/Xposed  (  304): -----------------
04-16 18:38:44.686 I/Xposed  (  304): Starting Xposed version 87 (MIUI edition by SolarWarez / 20161126), compiled for SDK 21
04-16 18:38:44.686 I/Xposed  (  304): Device: Redmi Note 2 (Xiaomi), Android version 5.0.2 (SDK 21)
04-16 18:38:44.686 I/Xposed  (  304): ROM: LRX22G
04-16 18:38:44.686 I/Xposed  (  304): Build fingerprint: Xiaomi/hermes/hermes:5.0.2/LRX22G/8.3.22:user/release-keys
04-16 18:38:44.686 I/Xposed  (  304): Platform: arm64-v8a, 64-bit binary, system server: yes
04-16 18:38:44.686 I/Xposed  (  304): SELinux enabled: yes, enforcing: yes
04-16 18:38:44.693 I/Xposed  (  304): -----------------
04-16 18:38:44.693 I/Xposed  (  304): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-16 18:38:44.958 I/Xposed  (  304): Detected ART runtime
04-16 18:38:44.967 I/Xposed  (  304): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-16 18:38:44.995 I/Xposed  (  304): MIUI detected... Make some patch...
04-16 18:38:44.995 I/Xposed  (  304): All done!
04-16 18:38:45.731 I/Xposed  (  304): Loading modules from /data/app/me.veryyoung.wechat.luckymoney-2/base.apk
04-16 18:38:45.746 I/Xposed  (  304):   Loading class me.veryyoung.wechat.luckymoney.Main
04-16 18:38:45.770 I/Xposed  (  304): Loading modules from /data/app/com.oasisfeng.greenify-1/base.apk
04-16 18:38:45.793 I/Xposed  (  304):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
04-16 18:38:45.813 I/Xposed  (  304):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
04-16 18:38:45.815 I/Xposed  (  304): Loading modules from /data/app/com.hhly.pay.alipay-1/base.apk
04-16 18:38:45.825 I/Xposed  (  304):   Loading class com.hhly.pay.alipay.Main
04-16 18:38:45.827 E/Xposed  (  304):     Failed to load class com.hhly.pay.alipay.Main
04-16 18:38:45.827 E/Xposed  (  304): java.lang.ClassNotFoundException: Didn't find class "com.hhly.pay.alipay.Main" on path: DexPathList[[zip file "/data/app/com.hhly.pay.alipay-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
04-16 18:38:45.827 E/Xposed  (  304): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-16 18:38:45.827 E/Xposed  (  304): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-16 18:38:45.827 E/Xposed  (  304): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-16 18:38:45.827 E/Xposed  (  304): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:1281)
04-16 18:38:45.827 E/Xposed  (  304): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:1211)
04-16 18:38:45.827 E/Xposed  (  304): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:91)
04-16 18:38:45.827 E/Xposed  (  304): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.hhly.pay.alipay.Main" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
04-16 18:38:45.827 E/Xposed  (  304): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-16 18:38:45.827 E/Xposed  (  304): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-16 18:38:45.827 E/Xposed  (  304): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-16 18:38:45.827 E/Xposed  (  304): 		... 4 more
04-16 18:38:45.827 E/Xposed  (  304): 		Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.hhly.pay.alipay.Main" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
04-16 18:38:45.827 E/Xposed  (  304): 			at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-16 18:38:45.827 E/Xposed  (  304): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-16 18:38:45.827 E/Xposed  (  304): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-16 18:38:45.827 E/Xposed  (  304): 			... 5 more
04-16 18:38:45.827 E/Xposed  (  304): 			Suppressed: java.lang.ClassNotFoundException: com.hhly.pay.alipay.Main
04-16 18:38:45.827 E/Xposed  (  304): 				at java.lang.Class.classForName(Native Method)
04-16 18:38:45.827 E/Xposed  (  304): 				at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-16 18:38:45.827 E/Xposed  (  304): 				at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-16 18:38:45.827 E/Xposed  (  304): 				at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-16 18:38:45.827 E/Xposed  (  304): 				... 6 more
04-16 18:38:45.827 E/Xposed  (  304): 			Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
04-16 18:38:53.884 I/Xposed  (  305): -----------------
04-16 18:38:53.884 I/Xposed  (  305): Starting Xposed version 87 (MIUI edition by SolarWarez / 20161126), compiled for SDK 21
04-16 18:38:53.884 I/Xposed  (  305): Device: Redmi Note 2 (Xiaomi), Android version 5.0.2 (SDK 21)
04-16 18:38:53.884 I/Xposed  (  305): ROM: LRX22G
04-16 18:38:53.884 I/Xposed  (  305): Build fingerprint: Xiaomi/hermes/hermes:5.0.2/LRX22G/8.3.22:user/release-keys
04-16 18:38:53.884 I/Xposed  (  305): Platform: arm64-v8a, 32-bit binary, system server: no
04-16 18:38:53.884 I/Xposed  (  305): SELinux enabled: yes, enforcing: yes
04-16 18:38:53.894 I/Xposed  (  305): -----------------
04-16 18:38:53.900 I/Xposed  (  305): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-16 18:38:54.225 I/Xposed  (  305): Detected ART runtime
04-16 18:38:54.239 I/Xposed  (  305): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-16 18:38:54.276 I/Xposed  (  305): MIUI detected... Make some patch...
04-16 18:38:54.276 I/Xposed  (  305): All done!
04-16 18:38:55.018 I/Xposed  (  305): Loading modules from /data/app/me.veryyoung.wechat.luckymoney-2/base.apk
04-16 18:38:55.837 I/Xposed  (  305):   Loading class me.veryyoung.wechat.luckymoney.Main
04-16 18:38:55.848 I/Xposed  (  305): Loading modules from /data/app/com.oasisfeng.greenify-1/base.apk
04-16 18:38:55.894 I/Xposed  (  305):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
04-16 18:38:55.915 I/Xposed  (  305):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
04-16 18:38:55.916 I/Xposed  (  305): Loading modules from /data/app/com.hhly.pay.alipay-1/base.apk
04-16 18:38:55.926 I/Xposed  (  305):   Loading class com.hhly.pay.alipay.Main
04-16 18:38:55.927 E/Xposed  (  305):     Failed to load class com.hhly.pay.alipay.Main
04-16 18:38:55.927 E/Xposed  (  305): java.lang.ClassNotFoundException: Didn't find class "com.hhly.pay.alipay.Main" on path: DexPathList[[zip file "/data/app/com.hhly.pay.alipay-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
04-16 18:38:55.927 E/Xposed  (  305): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-16 18:38:55.927 E/Xposed  (  305): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-16 18:38:55.927 E/Xposed  (  305): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-16 18:38:55.927 E/Xposed  (  305): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:1281)
04-16 18:38:55.927 E/Xposed  (  305): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:1211)
04-16 18:38:55.927 E/Xposed  (  305): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:91)
04-16 18:38:55.927 E/Xposed  (  305): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.hhly.pay.alipay.Main" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
04-16 18:38:55.927 E/Xposed  (  305): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-16 18:38:55.927 E/Xposed  (  305): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-16 18:38:55.927 E/Xposed  (  305): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-16 18:38:55.927 E/Xposed  (  305): 		... 4 more
04-16 18:38:55.927 E/Xposed  (  305): 		Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.hhly.pay.alipay.Main" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
04-16 18:38:55.927 E/Xposed  (  305): 			at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-16 18:38:55.927 E/Xposed  (  305): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-16 18:38:55.927 E/Xposed  (  305): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-16 18:38:55.927 E/Xposed  (  305): 			... 5 more
04-16 18:38:55.927 E/Xposed  (  305): 			Suppressed: java.lang.ClassNotFoundException: com.hhly.pay.alipay.Main
04-16 18:38:55.927 E/Xposed  (  305): 				at java.lang.Class.classForName(Native Method)
04-16 18:38:55.927 E/Xposed  (  305): 				at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-16 18:38:55.927 E/Xposed  (  305): 				at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-16 18:38:55.927 E/Xposed  (  305): 				at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-16 18:38:55.927 E/Xposed  (  305): 				... 6 more
04-16 18:38:55.927 E/Xposed  (  305): 			Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
04-16 18:39:42.687 I/Xposed  ( 3412): Found wechat version:6.6.5
04-16 18:39:43.995 E/Xposed  ( 3412): java.lang.NoSuchMethodError: com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyReceiveUI#d(int,int,java.lang.String,com.tencent.mm.ac.l)#exact
04-16 18:39:43.995 E/Xposed  ( 3412): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:341)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:182)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:257)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:142)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at android.app.ActivityThread.access$1600(ActivityThread.java:169)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at android.os.Handler.dispatchMessage(Handler.java:111)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at android.os.Looper.loop(Looper.java:194)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at android.app.ActivityThread.main(ActivityThread.java:5562)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at java.lang.reflect.Method.invoke(Native Method)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)
04-16 18:39:43.995 E/Xposed  ( 3412): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
04-16 18:40:44.559 I/Xposed  ( 6180): Found wechat version:6.6.5
04-16 18:40:45.493 E/Xposed  ( 6180): java.lang.NoSuchMethodError: com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyReceiveUI#d(int,int,java.lang.String,com.tencent.mm.ac.l)#exact
04-16 18:40:45.493 E/Xposed  ( 6180): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:341)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:182)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:257)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:142)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at android.app.ActivityThread.access$1600(ActivityThread.java:169)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at android.os.Handler.dispatchMessage(Handler.java:111)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at android.os.Looper.loop(Looper.java:194)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at android.app.ActivityThread.main(ActivityThread.java:5562)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at java.lang.reflect.Method.invoke(Native Method)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)
04-16 18:40:45.493 E/Xposed  ( 6180): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
04-16 18:40:48.396 I/Xposed  ( 6306): Found wechat version:6.6.5
04-16 18:40:48.575 E/Xposed  ( 6306): java.lang.NoSuchMethodError: com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyReceiveUI#d(int,int,java.lang.String,com.tencent.mm.ac.l)#exact
04-16 18:40:48.575 E/Xposed  ( 6306): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:341)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:182)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:257)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:142)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at android.app.ActivityThread.access$1600(ActivityThread.java:169)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at android.os.Handler.dispatchMessage(Handler.java:111)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at android.os.Looper.loop(Looper.java:194)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at android.app.ActivityThread.main(ActivityThread.java:5562)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at java.lang.reflect.Method.invoke(Native Method)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)
04-16 18:40:48.575 E/Xposed  ( 6306): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by 2449983723** [comment]
支付宝版本10.1.20

**Comment by 2449983723** [comment]
不同版本的支付宝的代码和混淆规则不一样

**Comment by litangyu** [comment]
经排查，关闭了AS的Instant Run 切换Gradle 和AS版本 问题解决。

开发环境 Android Studio 3.1.1 Gradle 4.4  Build Tools 27.0.3
